### PR TITLE
Added more to Positive Range

### PR DESCRIPTION
**Pull request by taibhse-design**
added higher sdp positive range upto 600sdp, had project where 300sdp
was not enough to make a UI element the size required.

I figured this change may be valuable especially with higher dpi devices.  I'm still pretty new to github and managing projects in this manner but I hope the addition is of use to others.

### CODE REVIEW

**Comment by elhanan-mishraky** [comment]
Thanks for your feedback! In the previous version the max was 600 but now you convinced me to restore it. You can now get up to 600 sdps using the new version - 1.0.3

**Comment by taibhse-design** [comment]
HI, thanks for adding my changes, its worth having having the higher number especially with higher dpi screens coming out, I was curious though, do you have any ideas for how this project could take into account screen aspect ratio's?

**Comment by elhanan-mishraky** [comment]
I could not find any solution for it yet. Can be helpful in some cases.

**Comment by taibhse-design** [comment]
it would be useful, I've encountered some issues where a menu would scale correctly on one screen but on another icons appear off and don't line up, no matter what values I use or point I have them align from,

**Pull request closed without merging**
