### PR TITLE
Added sdps for sw1080

### PR DESCRIPTION
**Pull request by despectra**

### CODE REVIEW

**Comment by elhanan-mishraky** [comment]
Hey @despectra, could you please share the situation where we need sw1080? Which device are you targeting?

**Comment by despectra** [comment]
Hey @elhanan-mishraky, we're currently working on digital signage apps for android and targeting devices with both sw 720 and 1080 (android settop boxes, odroid) that are used to render content to the LCD panels (1080 in most cases), so we're expecting our complex layouts to look consistent and proportional regardless of the screen size.

**Comment by elhanan-mishraky** [comment]
Thanks, merging.

**Comment by despectra** [comment]
Hey, what's about publishing the new version of your library to the maven repo? I can't wait to have those 1080 sdps available.

**Comment by elhanan-mishraky** [comment]
Will do next week, sorry for the delay.

**Comment by elhanan-mishraky** [comment]
Hey @despectra, I've just uploaded the new version (1.0.4) does it work for you?

**Pull request merged**
